name: Go Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          cache: true

      - name: Install golangci-lint
        run: |
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          golangci-lint --version

      - name: Run golangci-lint
        run: golangci-lint run --out-format checkstyle ./...
        
      - name: Convert checkstyle to CSV
        run: |
          golangci-lint run --out-format checkstyle ./... > checkstyle.xml
          cat checkstyle.xml | go run github.com/jstemmer/go-junit-report > lint-results.csv
